# Generated by Django 5.2 on 2025-09-05 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='Temp', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('advocate', 'Advocate'), ('sro', 'SRO'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='MetaDataCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('document_pending', 'Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search')], max_length=30)),
                ('legal_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='cases.branch')),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='cases.casetype')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='cases.employee')),
            ],
            options={
                'verbose_name': 'Meta Data Case',
                'verbose_name_plural': 'Meta Data Cases',
            },
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.metadatacase'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='cases.metadatacase'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
