# Generated by Django 5.2 on 2025-09-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_employee_options_employee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('documents_present', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('document_pending', 'Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('pending_assignment', 'Pending Assignment')], default='pending_assignment', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_advocate', models.ForeignKey(blank=True, limit_choices_to={'employee_type': 'advocate'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to='cases.employee')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.bank')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='cases.branch')),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casetype')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='cases.employee')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='cases.case'),
        ),
        migrations.DeleteModel(
            name='MetaDataCase',
        ),
    ]
