# Generated by Django 5.2 on 2025-09-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_alter_caseupdate_case_alter_remark_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='forwarded_to_sro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='action',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cases', to='cases.case')),
            ],
            options={
                'verbose_name': 'Sub Case',
                'verbose_name_plural': 'Sub Cases',
            },
        ),
    ]
