# Generated by Django 5.2 on 2025-09-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_completed_at_case_forwarded_to_sro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_cases', to='cases.case'),
        ),
        migrations.DeleteModel(
            name='SubCase',
        ),
    ]
