# Generated by Django 5.2 on 2025-09-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_parent_case_delete_subcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to='cases.employee'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('document_pending', 'Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
