# Generated by Django 5.2 on 2025-09-13 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caseupdate_updated_by_alter_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseupdate',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='bank',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='bank_documents/'),
        ),
        migrations.AddField(
            model_name='bank',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('name', 'state')},
        ),
        migrations.CreateModel(
            name='BankCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_case_types', to='cases.bank')),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_case_types', to='cases.casetype')),
            ],
            options={
                'unique_together': {('bank', 'case_type')},
            },
        ),
        migrations.DeleteModel(
            name='BranchCaseType',
        ),
    ]
