# Generated by Django 5.2 on 2025-09-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_caseupdate_updated_by_bank_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='document',
        ),
        migrations.CreateModel(
            name='BankDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bank_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.bank')),
            ],
        ),
    ]
