# Generated by Django 5.2 on 2025-09-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_remove_employee_aadhar_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_quotation',
            field=models.BooleanField(default=False, help_text='Indicates this case started as a quotation (no documents yet)'),
        ),
        migrations.AddField(
            model_name='case',
            name='quotation_finalized',
            field=models.BooleanField(default=False, help_text='Quotation confirmed, ready for assignment and document collection'),
        ),
        migrations.AddField(
            model_name='case',
            name='quotation_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quoted price (can be updated until finalized)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('document_pending', 'Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
