# Generated by Django 5.2 on 2025-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_casedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initials',
            field=models.CharField(blank=True, help_text='Two-letter initials (e.g., AB)', max_length=2, null=True),
        ),
    ]
