# Generated by Django 5.2 on 2025-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_employee_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number (no spaces)', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, help_text='10-character PAN (AAAAA9999A)', max_length=10, null=True),
        ),
    ]
