# Generated by Django 5.2 on 2025-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_employee_aadhaar_number_employee_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN (optional)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN (optional)', max_length=10, null=True),
        ),
    ]
