# Generated by Django 5.2 on 2025-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_state_district_tehsil'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='receipt_expense',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Receipt expense amount (optional)', max_digits=10, null=True),
        ),
    ]
