# Generated by Django 5.2 on 2025-10-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_case_receipt_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_sro',
            field=models.ForeignKey(blank=True, limit_choices_to={'employee_type': 'sro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sro_cases', to='cases.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_districts',
            field=models.ManyToManyField(blank=True, related_name='sro_allowed_districts', to='cases.district'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_states',
            field=models.ManyToManyField(blank=True, related_name='sro_allowed_states', to='cases.state'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_tehsils',
            field=models.ManyToManyField(blank=True, related_name='sro_allowed_tehsils', to='cases.tehsil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_super_sro',
            field=models.BooleanField(default=False, help_text='If true, SRO can see and manage all SRO cases'),
        ),
    ]
