# Generated by Django 5.2 on 2025-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_case_assigned_sro_employee_allowed_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assigned_sro',
        ),
        migrations.AddField(
            model_name='case',
            name='is_school_case',
            field=models.BooleanField(default=False, help_text='Mark if this is a school case for duplicate checks'),
        ),
    ]
