# Generated by Django 5.2 on 2025-10-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_bankextrafee_casecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload the supporting document for this work', upload_to='case_documents/')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='cases.case')),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_works', to='cases.casetype')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
