# Generated by Django 5.2 on 2025-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_casework'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='original_custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override fee for original case type (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='casework',
            name='custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
