# Generated by Django 5.2 on 2025-10-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_case_original_custom_fee_casework_custom_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_fees', to='cases.case')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
