# Generated by Django 5.2 on 2025-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_adhocfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecharge',
            name='bank_extra_fee',
        ),
        migrations.RemoveField(
            model_name='casecharge',
            name='case',
        ),
        migrations.DeleteModel(
            name='BankExtraFee',
        ),
        migrations.DeleteModel(
            name='CaseCharge',
        ),
    ]
