# Generated by Django 5.2 on 2025-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_remove_casecharge_bank_extra_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='is_receipt',
            field=models.BooleanField(default=False),
        ),
    ]
