# Generated by Django 5.2 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_casedocument_is_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('document_pending', 'Document Pending'), ('sro_document_pending', 'SRO Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
