# Generated by Django 5.2 on 2025-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
