# Generated by Django 5.2 on 2025-11-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_bankbranch_state'),
        ('cases', '0026_case_reassigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='Bank.bank'),
        ),
        migrations.AlterField(
            model_name='case',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_data_cases', to='Bank.bankbranch'),
        ),
        migrations.DeleteModel(
            name='BankDocument',
        ),
        migrations.DeleteModel(
            name='BankCaseType',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
