# Generated by Django 5.2 on 2025-12-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_alter_bank_unique_together_remove_bankcasetype_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quotation', 'Quotation'), ('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('query', 'Query'), ('document_pending', 'Document Pending'), ('sro_document_pending', 'SRO Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
