# Generated by Django 5.2 on 2025-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_add_is_final_to_casedocument'),
        ('cases', '0028_alter_case_status'),
    ]

    operations = [
    ]
