# Generated by Django 5.2 on 2025-12-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_merge_20251213_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quotation', 'Quotation'), ('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('query', 'Query'), ('document_pending', 'Document Pending'), ('sro_document_pending', 'SRO Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('draft_positive_subject_tosearch', 'Draft Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
