# Generated by Django 5.2 on 2025-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('case_number', 'case_type')},
        ),
    ]
