# Generated by Django 5.2 on 2026-01-11 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_alter_case_case_number_alter_case_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_sro',
            field=models.ForeignKey(blank=True, limit_choices_to={'employee_type': 'sro'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sro_cases', to='cases.employee'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quotation', 'Quotation'), ('positive', 'Positive'), ('negative', 'Negative'), ('on_hold', 'On Hold'), ('on_query', 'On Query'), ('query', 'Query'), ('document_pending', 'Document Pending'), ('sro_document_pending', 'SRO Document Pending'), ('positive_subject_tosearch', 'Positive Subject to Search'), ('draft_positive_subject_tosearch', 'Draft Positive Subject to Search'), ('pending_assignment', 'Pending Assignment'), ('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=50),
        ),
    ]
