# Generated by Django 5.2 on 2025-11-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0026_case_reassigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankStateCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('casetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.casetype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bank', 'state', 'casetype'), name='uniq_bank_state_casetype'), models.UniqueConstraint(condition=models.Q(('casetype__isnull', True)), fields=('bank', 'state'), name='uniq_bank_state_null_casetype')],
            },
        ),
    ]
