# Generated by Django 5.2 on 2025-11-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
        ('cases', '0026_case_reassigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bank State',
                'verbose_name_plural': 'Bank States',
            },
        ),
        migrations.AlterModelOptions(
            name='bankstatecasetype',
            options={'verbose_name': 'Bank State Case Type Fee', 'verbose_name_plural': 'Bank State Case Type Fees'},
        ),
        migrations.RemoveConstraint(
            model_name='bankstatecasetype',
            name='uniq_bank_state_casetype',
        ),
        migrations.RemoveConstraint(
            model_name='bankstatecasetype',
            name='uniq_bank_state_null_casetype',
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bankstatecasetype',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_case_type_fees', to='Bank.bank'),
        ),
        migrations.AlterField(
            model_name='bankstatecasetype',
            name='casetype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bank_state_fees', to='cases.casetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankstatecasetype',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_case_type_fees', to='cases.state'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatecasetype',
            unique_together={('bank', 'state', 'casetype')},
        ),
        migrations.AddField(
            model_name='bankstate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_states', to='Bank.bank'),
        ),
        migrations.AddField(
            model_name='bankstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_banks', to='cases.state'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstate',
            unique_together={('bank', 'state')},
        ),
    ]
