# Generated by Django 5.2 on 2025-11-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_bankstate_alter_bankstatecasetype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Bank.bank')),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
                'ordering': ['name'],
            },
        ),
    ]
