# Generated by Django 5.2 on 2025-11-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_bankbranch'),
        ('cases', '0026_case_reassigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_branches', to='cases.state'),
        ),
    ]
