# Generated by Django 5.2 on 2025-11-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_bankbranch_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='bank_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Bank.bank')),
            ],
            options={
                'verbose_name': 'Bank Document',
                'verbose_name_plural': 'Bank Documents',
                'ordering': ['-uploaded_at', 'id'],
            },
        ),
    ]
